# Dataset
program: train.py
method: bayes
project: HPO_Demo
metric:
    name: auc.max
    goal: maximize
parameters:
    # Model hyperparameters
    nb_edge_layers:
        min: 1
        max: 4
    nb_node_layers:
        min: 1
        max: 4
    nb_graph_iters:
        min: 2
        max: 10
    hidden:
        min: 16
        max: 256
    hidden_activation:
        values: [ReLU, SiLU, Tanh]
    layer_norm:
        values: [False, True]
        
    # Training hyperparameters
    lr: 
        distribution: log_uniform
        min: -11
        max: -3
    patience: 
        min: 1
        max: 25
    factor: 
        min: 0.1
        max: 0.9
        
# Early stopping
early_terminate:
    type: hyperband
    min_iter: 3